# Generated by Django 3.0.7 on 2020-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
