# Generated by Django 3.0.7 on 2020-06-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
